name: Deploy to Cloudflare Workers

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          wranglerVersion: '3.90.0'
          preCommands: |
            # Clean up any existing KV namespaces
            wrangler kv:namespace list || true
            # Only upload changed files
            git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
