name: Deploy to Cloudflare

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ini penting untuk git diff

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install Wrangler
        run: npm install -g wrangler@3.90.0

      - name: Deploy Worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        run: |
          # Check if environment variables are set
          if [ -z "$CLOUDFLARE_API_TOKEN" ]; then
            echo "Error: CLOUDFLARE_API_TOKEN is not set"
            exit 1
          fi
          
          if [ -z "$CF_ACCOUNT_ID" ]; then
            echo "Error: CF_ACCOUNT_ID is not set"
            exit 1
          fi
          
          if [ -z "$CF_ZONE_ID" ]; then
            echo "Error: CF_ZONE_ID is not set"
            exit 1
          fi
          
          # Deploy using wrangler
          wrangler deploy --minify
