name: Build and Publish 

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Pastikan semua commit ditarik untuk rebase

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test build output
        run: |
          if [ ! -d "dist" ]; then
            echo "dist directory not found"
            exit 1
          fi
          ls -la dist

      - name: Auto-update version
        run: |
          NEW_VERSION=$(npm version patch --no-git-tag-version)
          echo "New version: $NEW_VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV  # Simpan sebagai variabel lingkungan

      - name: Publish to NPM
        if: success()
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit updated version
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Tarik perubahan terbaru dari remote sebelum push
          git pull --rebase origin main

          git add package.json
          git commit -m "Bump version to $NEW_VERSION [skip ci]" || echo "No changes to commit"
          git push origin main  # Pastikan push dilakukan ke branch yang benar

      - name: Create GitHub Release
        if: success()
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Mental Health v-${{ github.run_number }}
          body: |
            Mental Health App with Emotion Detection
            
            Built and published automatically via GitHub Actions
          draft: false
          prerelease: false
