name: Security Hardening
on: [push, schedule]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Erlang
        uses: erlef/setup-beam@v1
        
      - name: Run Security Systems
        run: |
          erl -noshell -eval '
            application:start(crypto),
            code:load_file(ip_blocker),
            code:load_file(security_monitor),
            ip_blocker:start_link(),
            security_monitor:start(),
            % Auto-block IPs dari daftar known bad actors
            lists:foreach(fun(IP) -> ip_blocker:block_ip(IP) end, [
                "1.1.1.1", "2.2.2.2" % Contoh IP berbahaya
            ]),
            init:stop()
          '
          
      - name: Deploy WAF Rules
        run: |
          curl -X PUT "https://api.cloudflare.com/client/v4/zones/bab32fe292310337a52c8dbaac93e34a/firewall/rules" \
          -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_KEY }}" \
          -H "Content-Type: application/json" \
          --data '{
            "rules": [{
              "filter": {
                "expression": "(http.request.uri.path contains \"/wp-admin\")"
              },
              "action": "block"
            }]
          }'
